# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fit And Easy - Physiotherapy and Power Plate Studio
description: > # this means to ignore newlines until "baseurl:"
  A dedicated Power Plate studio just five minutes from Southampton city centre, Fit & Easy is clean, bright and calm, offering you the chance to get-away from it all, even if it is for only half an hour.
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

incremental: true
